apiVersion: v1
kind: Service
metadata:
  name: auralog
  namespace: auralog
spec:
  selector:
    app: auralog
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
    - name: udp-ingest
      port: 9000
      targetPort: udp-ingest
      protocol: UDP
